openapi: 3.0.1
info:
  title: Notiver CEIMS Unified API
  version: 1.0.0


x-amazon-apigateway-cors:
  allowOrigins:
    - "https://main.d2exnodyaugt1a.amplifyapp.com"
    - "http://localhost:3000"
  allowMethods:
    - "GET"
    - "POST"
    - "OPTIONS"
    - "PUT"
    - "DELETE"
  allowHeaders:
    - "content-type"
    - "authorization"
    - "x-amz-date"
    - "x-api-key"
    - "x-amz-security-token"
  maxAge: 300
  allowCredentials: true

  
paths:
  # --- DATA COLLECTION SERVICE ---
  /data-collection/{proxy+}:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:${AWS_ACCOUNT_ID}:function:data-collection-function/invocations"

  # --- DATA PROCESSING SERVICE ---
  /data-processing/{proxy+}:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:${AWS_ACCOUNT_ID}:function:data-nlp-analytics/invocations"

  # --- DATA RETRIEVAL SERVICE ---
  /data-retrieval/{proxy+}:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:${AWS_ACCOUNT_ID}:function:data-retrieval-function/invocations"