export const MAJOR_CITIES = [
  "NSW, Australia (CEIMS)",
  "London, UK",
  "Dubai, UAE",
  "Tehran, Iran",
  "Tokyo, Japan",
  "Paris, France",
  "Hong Kong, China",
  "Singapore",
  "Shanghai, China",
  "Seoul, South Korea",
  "Bangkok, Thailand",
  "Istanbul, Turkey",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Amsterdam, Netherlands",
  "Zurich, Switzerland",
  "Vienna, Austria",
  "Dublin, Ireland",
  "Frankfurt, Germany",
  "Munich, Germany",
  "Brussels, Belgium",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "San Francisco, USA",
  "Chicago, USA",
  "Boston, USA",
  "Seattle, USA",
  "Washington DC, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Mexico City, Mexico",
  "São Paulo, Brazil",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Kuwait City, Kuwait",
  "Abu Dhabi, UAE",
  "Tel Aviv, Israel",
  "Cairo, Egypt",
  "Johannesburg, South Africa",
  "Nairobi, Kenya"
];